amazon:
  region: ap-northeast-2
  accessKey: testAccessKey
  secretKey: testSecretKey
  dynamodb:
    endpoint: http://localhost:8000
    tablePrefix: local-
    tables:
      vendor:
        ttlinhrs: 2
