package com.example.sample.models

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.example.sample.util.InstantConverter
import java.time.Instant

@DynamoDBTable(tableName = "product")
data class ProductDocument(

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    var id: String? = null,

    @DynamoDBAttribute
    var name: String = "",

    @DynamoDBAttribute
    var price: Long = 0,

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = InstantConverter::class)
    var createdAt: Instant = Instant.now(),

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = InstantConverter::class)
    var updatedAt: Instant = Instant.now()

)
